description: Runs the Training Wheels Protocol tests
sessionLabel: Training Wheels Protocol tests
maxIterations: 1
tests:
    - name: Training Wheels Protocol - Checkboxes test
      path: web

    - name: Training Wheels Protocol - Drag and drop test
      path: web

    - name: Training Wheels Protocol - Radio button test
      path: web

    - name: Training Wheels Protocol - Select2 test
      path: web

    - name: Training Wheels Protocol - Select2 multiple test
      path: web

    - name: Training Wheels Protocol - Dynamic controls test
      path: web

    - name: Training Wheels Protocol - Login test
      path: web

    - name: Training Wheels Protocol - Login2 test
      path: web

    - name: Training Wheels Protocol - Register user test
      path: web

    - name: Training Wheels Protocol - Hovers
      path: web
