description: Runs the Training Wheels Protocol tests
sessionLabel: Training Wheels Protocol tests
maxIterations: 1
tests:
    - name: Training Wheels Protocol - Checkboxes test
      path: web

    - name: Training Wheels Protocol - Drag and drop test
      path: web

    - name: Training Wheels Protocol - Radio button test
      path: web